<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-28T18:16:18+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'en_GB',
    'version_installed' => '8.1.0',
    'version_db_installed' => '20170123000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1485956297,
        'latest_version' => '8.1.0',
        'do_page_reindex_check' => false,
    ],
];
